### ISSUE TITLE
"Error: No type conversion found for 'DNSDomainFromDHCP_NICStaticTypes.Disabled'. Expected DNSDomainNameFromDHCP_NICTypes. Got DNSDomainFromDHCP_NICStaticTypes"

### ISSUE THREAD

**Issue by gedia** [dell/Dell-EMC-Ansible-Modules-for-iDRAC#10]
I'm getting the following error with iDRAC 2.60.60.60 and the latest devel (1.0.4) version of dellemc_configure_idrac_network module.

I believe this used to work with 1.0.3, although that version seems to have other bugs for which I'll open a separate ticket if they persist in 1.0.4.

**Comment by gedia** [comment]
P.S. The other bugs I found in 1.0.3 seem to be fixed in 1.0.4.

I was able to work around this bug by substituting all instances of 'DNSDomainFromDHCP_NICStaticTypes' with 'DNSDomainNameFromDHCP_NICTypes' in dellemc_configure_idrac_network.py

**Comment by rajeevarakkal** [comment]
As this issue is resolved in 1.0.4 release. I am closing the defect.

Lets us know in case you need further support 

Thanks
Rajeev

**Comment by gedia** [comment]
I've just tested v1.0.4 from the release archive and I'm still getting this...
